name: AccountCreator

on:
  repository_dispatch:
    types: [newuser]

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      USER: ${{ github.event.client_payload.user }}
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: Executar script
        run: |
          echo "PASS=${{ github.event.client_payload.PASS }}" >> $GITHUB_ENV
          lua .github/workflows/accountservicecode.lua