name: DOT Buddy

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: install lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: run bot code
        run: lua .github/workflows/botcode.lua
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          PAT: ${{ secrets.PAT }}
          ISSUE_NUMBER: {{ github.event.issue.number }}