name: DOT Buddy

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Instalar Lua
      - name: Instalar Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      # Rodar botcode.lua que est√° na mesma pasta que o YML
      - name: Rodar botcode.lua
        run: lua botcode.lua
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ISSUE_NUMBER: 7