name: IssueService

on:
  repository_dispatch:
    types: [comment]

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      USER: ${{ github.event.client_payload.user }}
      PAT: ${{ secrets.PAT }}
      ISSUE: ${{ github.event.client_payload.issue }}
      CONTENT: ${{ github.event.client_payload.content }}
      ACTION: ${{ github.event.client_payload.action }}
      

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: Executar script
        run: |
          export PASS="${{ github.event.client_payload.pass }}"
          
          lua .github/workflows/issueservicecode.lua