name: IssueComment

on:
  repository_dispatch:
    types: [newcomment]

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      USER: ${{ github.event.client_payload.user }}
      PAT: ${{ secrets.PAT }}
      ISSUE: ${{ github.event.client_payload.issue }}
      CONTENT: ${{ github.event.client_payload.content }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: Executar script
        run: |
          PASS="${{ github.event.client_payload.pass }}"
          ACTION="comment-new"
          
          lua .github/workflows/issueservicecode.lua