name: Post Service

on:
  repository_dispatch:
    types: [unauth_put_attempt]

jobs:
  observe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: Run printer.lua
        env:
          ASK: ${{ secrets.ASK }}
        run: lua PostService.lua