name: ServiceManager

on:
  repository_dispatch:
    types: [post]

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      USER: ${{ github.event.client_payload.user }}
      FILE: ${{ github.event.client_payload.file }}
      CONTENT: ${{ github.event.client_payload.content }}
      MODE: ${{ github.event.client_payload.mode }}
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4

      - name: Executar script
        run: |
          export PASS="${{ github.event.client_payload.pass }}"
          lua .github/workflows/serviceprocessorcode.lua